### ISSUE TITLE
AOI has a missing polygon

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#201]
When looking at the upper part of the AOI for Tajikistan, react leaflet component Polygon is not rendering the AOI as it should: A sub part of the polygon is missing.

I noticed this bug a long time ago and reordered the polygon in the aoi.gejson file, because it will only render the first element it "sees" apparently. However, when I open the AOI file in another program, such as QGIS, it will render all the elements of the AOI. 

![aoi_bug](https://user-images.githubusercontent.com/38685413/201363258-0527e636-6674-476e-81e6-3c1a25cae4f6.PNG)

When opened in QGIS looks correct:

![image](https://user-images.githubusercontent.com/38685413/201363401-0ae96c8f-8906-46d6-88a2-54ac72bc564f.png)

**Comment by andreiPro** [comment]
Hi Team,
Working on.

**Comment by andreiPro** [comment]
Good morning Martin,
Done. 
Only 1 layer out of 3 was displayed because all three unrelated/independent layers were included in the same Feature object. After I placed each layer in a separate Feature object, everything started working.
<img width="757" alt="Screen Shot 2022-11-20 at 12 47 12 AM" src="https://user-images.githubusercontent.com/64378048/202889947-39f8fbf2-10c9-489b-bdfd-cef92bd22874.png">

`"features": [ 
{ "type": "Feature", "properties": { }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ ] ] ]`},
{ "type": "Feature", "properties": { }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ ] ] ]`},
{ "type": "Feature", "properties": { }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ ] ] ]}]`
